// Nicknamed 'Dragon Cum' for a reason. - [Ted]
class CC_Alcohol_CreamedWhiskey : UaS_Alcohol
{
    mixin CC_AlcoholMixin;

    default
    {
        UaS_Consumable.Calories 1652;
        UaS_Consumable.Fluid 701;
        UaS_Consumable.Bulk 17;
        UaS_Consumable.OpenSound "mre/cork";
        
        Inventory.Icon "BTTLD0";
        Inventory.PickupMessage "$CC_CREAMEDWHISKEY_PICKUP";

        tag "$CC_CREAMEDWHISKEY_TAG";
        Uas_Consumable.Description "$CC_CREAMEDWHISKEY_DESCRIPTION";
        UaS_Alcohol.IntoxPerBulk 77;

        Scale 0.5;
    }
    override void Messages()
    {
        AddOpenText(Stringtable.Localize("$CC_CREAMEDWHISKEY_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_CREAMEDWHISKEY_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_CREAMEDWHISKEY_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_CREAMEDWHISKEY_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_CREAMEDWHISKEY_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_CREAMEDWHISKEY_CONSUME4"));
        AddConsumeText(Stringtable.Localize("$CC_CREAMEDWHISKEY_CONSUME5"));
    }
    
    states
    {
        Spawn:
            BTTL D -1;
            Stop;
    }
}

class CC_Alcohol_Kahlua : UaS_Alcohol
{
    mixin CC_AlcoholMixin;

    default
    {
        UaS_Consumable.Calories 1021;
        UaS_Consumable.Fluid 192;
        UaS_Consumable.Bulk 16;
        UaS_Consumable.OpenSound "mre/cork";

        Inventory.Icon "BTTLC0";

        tag "$CC_KAHLUA_TAG";
        Uas_Consumable.Description "$CC_KAHLUA_DESCRIPTION";
        UaS_Alcohol.IntoxPerBulk 34;

        Scale 0.5;
    }

    override void Messages()
    {
        AddOpenText(Stringtable.Localize("$CC_KAHLUA_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_KAHLUA_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_KAHLUA_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_KAHLUA_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_KAHLUA_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_KAHLUA_CONSUME4"));
        AddConsumeText(Stringtable.Localize("$CC_KAHLUA_CONSUME5"));
        AddConsumeText(Stringtable.Localize("$CC_KAHLUA_CONSUME6"));
    }
}

class CC_Drink_BAS : UaS_Consumable
{
    mixin CC_BottledDrinkMixin;

    default
    {
        Inventory.Icon "BTTLC0";

        tag "$CC_BAS_TAG";
        Uas_Consumable.Description "$CC_BAS_DESCRIPTION";

        Scale 0.5;
    }

    override void Messages()
    {
        AddOpenText(Stringtable.Localize("$CC_BAS_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_BAS_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_BAS_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_BAS_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_BAS_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_BAS_CONSUME4"));
        AddConsumeText(Stringtable.Localize("$CC_BAS_CONSUME5"));
        AddConsumeText(Stringtable.Localize("$CC_BAS_CONSUME6"));
    }
}

class CC_Alcohol_Gonster : UaS_Alcohol
{
    mixin CC_AlcoholMixin;

    default
    {
        UaS_Consumable.Calories 812;
        UaS_Consumable.Fluid 1321;
        UaS_Consumable.Bulk 16;
        UaS_Consumable.OpenSound "mre/cork";

        Inventory.Icon "BTTLB0";

        tag "$CC_GONSTER_TAG";
        Uas_Consumable.Description "$CC_GONSTER_DESCRIPTION";
        UaS_Alcohol.IntoxPerBulk 192;

        Scale 0.75;
    }

    override void Messages()
    {
        AddOpenText(Stringtable.Localize("$CC_GONSTER_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_GONSTER_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_GONSTER_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_GONSTER_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_GONSTER_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_GONSTER_CONSUME4"));
        AddConsumeText(Stringtable.Localize("$CC_GONSTER_CONSUME5"));
        AddConsumeText(Stringtable.Localize("$CC_GONSTER_CONSUME6"));
    }
}