// I never put a single other seasoning other than the storebought seasoning in tacos -- [Kattie]
class CC_PlateTacos : UaS_Consumable
{
    mixin CC_PlatedMixin;

    default
    {
        tag "$CC_TACOS_TAG";
        Uas_Consumable.Calories 470; 
        UaS_Consumable.Description "$CC_TACOS_DESCRIPTION";
    }
    override void Messages() {
		AddOpenText(Stringtable.Localize("$CC_TACOS_OPEN1"));
		AddOpenText(Stringtable.Localize("$CC_TACOS_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME4"));
	}

}

class CC_Murphy_Slaw : UaS_Consumable
{
    mixin CC_PlatedMixin;

    default
    {
        tag "$CC_MURPHYSLAW_TAG";
        UaS_Consumable.Calories 623;
        UaS_Consumable.Fluid 92;
        UaS_Consumable.Description "$CC_MURPHYSLAW_DESCRIPTION";
    }

    override void Messages() {
		AddOpenText(Stringtable.Localize("$CC_MURPHYSLAW_OPEN1"));
		AddOpenText(Stringtable.Localize("$CC_MURPHYSLAW_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME4"));
	}
}

class CC_Roundmeal : UaS_Consumable
{
    mixin CC_BaggedMREMixin;

    default
    {
        tag "$CC_ROUNDMEAL_TAG";
        UaS_Consumable.Calories 2691;
        UaS_Consumable.Fluid 492;
        UaS_Consumable.Description "$CC_ROUNDMEAL_DESCRIPTION";
        Scale 1.2;
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_ROUNDMEAL_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_ROUNDMEAL_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME4"));
    }
}

class CC_HumanFingers : UaS_Consumable
{
    mixin CC_BaggedMREMixin;

    default
    {
        tag "$CC_HUMANFINGERS_TAG";
        UaS_Consumable.Calories 319;
        UaS_Consumable.Fluid 2;
        UaS_Consumable.Description "$CC_HUMANFINGERS_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_HUMANFINGERS_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_HUMANFINGERS_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME4"));
    }
}

class CC_Ceviche : UaS_Consumable
{
    mixin CC_ComfortMREMixin;

    default
    {
        tag "$CC_CEVICHE_TAG";
        UaS_Consumable.Calories 812;
        UaS_Consumable.Fluid -492;
        Uas_Consumable.Bulk 8;
        UaS_Consumable.Description "$CC_CEVICHE_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_CEVICHE_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_CEVICHE_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME4"));
    }
}