// I never put a single other seasoning other than the storebought seasoning in tacos -- [Kattie]
class CC_PlateTacos : UaS_Consumable
{
    mixin CC_PlatedMixin;

    default
    {
        tag "$CC_TACOS_TAG";
        Uas_Consumable.Calories 470; 
        UaS_Consumable.Description "$CC_TACOS_DESCRIPTION";
    }
    override void Messages() {
		AddOpenText(Stringtable.Localize("$CC_TACOS_OPEN1"));
		AddOpenText(Stringtable.Localize("$CC_TACOS_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_TACOS_CONSUME4"));
	}

}

class CC_Murphy_Slaw : UaS_Consumable
{
    mixin CC_PlatedMixin;

    default
    {
        tag "$CC_MURPHYSLAW_TAG";
        UaS_Consumable.Calories 623;
        UaS_Consumable.Fluid 92;
        UaS_Consumable.Description "$CC_MURPHYSLAW_DESCRIPTION";
    }

    override void Messages() {
		AddOpenText(Stringtable.Localize("$CC_MURPHYSLAW_OPEN1"));
		AddOpenText(Stringtable.Localize("$CC_MURPHYSLAW_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_MURPHYSLAW_CONSUME4"));
	}
}

class CC_Roundmeal : UaS_Consumable
{
    mixin CC_BaggedMREMixin;

    default
    {
        tag "$CC_ROUNDMEAL_TAG";
        UaS_Consumable.Calories 2691;
        UaS_Consumable.Fluid 492;
        UaS_Consumable.Description "$CC_ROUNDMEAL_DESCRIPTION";
        Scale 1.2;
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_ROUNDMEAL_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_ROUNDMEAL_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_ROUNDMEAL_CONSUME4"));
    }
}

class CC_HumanFingers : UaS_Consumable
{
    mixin CC_BaggedMREMixin;

    default
    {
        tag "$CC_HUMANFINGERS_TAG";
        UaS_Consumable.Calories 319;
        UaS_Consumable.Fluid 2;
        UaS_Consumable.Description "$CC_HUMANFINGERS_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_HUMANFINGERS_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_HUMANFINGERS_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_HUMANFINGERS_CONSUME4"));
    }
}

class CC_Ceviche : UaS_Consumable
{
    mixin CC_ComfortMREMixin;

    default
    {
        tag "$CC_CEVICHE_TAG";
        UaS_Consumable.Calories 812;
        UaS_Consumable.Fluid -492;
        Uas_Consumable.Bulk 8;
        UaS_Consumable.Description "$CC_CEVICHE_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_CEVICHE_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_CEVICHE_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_CEVICHE_CONSUME4"));
    }
}

class CC_DinkiDi : UaS_Consumable
{
    mixin CC_ComfortMREMixin;

    default
    {
        tag "$CC_DINKIDI_TAG";
        UaS_Consumable.Calories 1644;
        UaS_Consumable.Fluid 381;
        UaS_Consumable.Bulk 10;
        UaS_Consumable.SpoilRate 0.25;
        UaS_Consumable.Description "$CC_DINKIDI_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_DINKIDI_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_DINKIDI_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_DINKIDI_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_DINKIDI_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_DINKIDI_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_DINKIDI_CONSUME4"));
    }
}

class CC_OminousGoop : UaS_Consumable
{
    mixin CC_ComfortMREMixin;
	int prevbulk;

    default
    {
        tag "$CC_OMINOUSGOOP_TAG";
        UaS_Consumable.Calories 2913;
        UaS_Consumable.Fluid 3194;
        UaS_Consumable.Bulk 45;
        UaS_Consumable.SpoilRate 1.25;
        UaS_Consumable.Description "$CC_OMINOUSGOOP_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_OMINOUSGOOP_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_OMINOUSGOOP_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_OMINOUSGOOP_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_OMINOUSGOOP_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_OMINOUSGOOP_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_OMINOUSGOOP_CONSUME4"));
    }


	override void Tick()
	{
		Super.tick();

		if(!tracker || !tracker.owner)
			return;
		HDPlayerPawn hdp = HDPlayerPawn(tracker.owner);
		int bulk = prevbulk - weaponbulk();
		if(bulk > 0){
            switch(random(0,13))
            {
                default: break;
			    case 0: hdp.GiveInventory("GoopShield", 1); HDMagicShield.FlashSparks(owner); owner.A_Log("Fuck, spilled some..."); break;
			    case 1: hdp.bloodloss=max(0,hdp.bloodloss-random(4,20)); if(hdp.fatigue<HDCONST_SPRINTFATIGUE)hdp.fatigue+random(1,5); A_Log("That's not sitting right..."); break;
                case 2: owner.A_GiveInventory("HealingMagic",HDHM_MOUTH); owner.A_Log("I feel funny..."); break;
            }
		}
		prevbulk = weaponbulk();
	}
}

class GoopShield:HDMagicShield{
	default{
		+nointeraction +noblockmap

		-quicktoretaliate  //if enabled, regenerate up to maxamount
		-standstill  //if enabled, do not deplete if over maxamount
		+inventory.keepdepleted

		inventory.amount 1;
		inventory.maxamount 150;
		inventory.icon "BON2A0";

		stamina 0;  //if set, this is the strength of the shield; otherwise use maxamount

		HDDamageHandler.priority 5000;
		+hdpickup.fullcoverage
	}
}

class CC_Haggis : UaS_Consumable
{
    mixin CC_ComfortMREMixin;

    default
    {
        tag "$CC_HAGGIS_TAG";
        UaS_Consumable.Calories 1984;
        UaS_Consumable.Fluid -194;
        UaS_Consumable.Bulk 12;
        UaS_Consumable.Description "$CC_HAGGIS_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_HAGGIS_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_HAGGIS_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_HAGGIS_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_HAGGIS_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_HAGGIS_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_HAGGIS_CONSUME4"));
    }
}

class CC_CheeseSandwich : UaS_Consumable
{
    mixin CC_ComfortMREMixin;

    default
    {
        tag "$CC_CHEESESANDWICH_TAG";
        UaS_Consumable.Calories 584;
        UaS_Consumable.Fluid -230;
        UaS_Consumable.Bulk 3;
        UaS_Consumable.Description "$CC_CHEESESANDWICH_DESCRIPTION";
    }

    override void Messages() {
        AddOpenText(Stringtable.Localize("$CC_CHEESESANDWICH_OPEN1"));
        AddOpenText(Stringtable.Localize("$CC_CHEESESANDWICH_OPEN2"));

        AddConsumeText(Stringtable.Localize("$CC_CHEESESANDWICH_CONSUME1"));
        AddConsumeText(Stringtable.Localize("$CC_CHEESESANDWICH_CONSUME2"));
        AddConsumeText(Stringtable.Localize("$CC_CHEESESANDWICH_CONSUME3"));
        AddConsumeText(Stringtable.Localize("$CC_CHEESESANDWICH_CONSUME4"));
    }
}