mixin class CC_AlcoholMixin
{
    default
    {
        Uas_Consumable.Calories 31;
        Uas_Consumable.Fluid 417;
        Uas_Consumable.Bulk 9;

        +Uas_Consumable.DRINKABLE;
        +Uas_Consumable.PACKAGED;
        +UaS_Consumable.RESEALABLE;
        
        Inventory.PickupMessage "$CC_ALCHMIXIN_PICKUP";

        Inventory.Icon "HSCVZ0";
        scale 0.85;
    }
}

mixin class CC_PlatedMixin
{
    default
    {
        Uas_Consumable.Calories 400;
        Uas_Consumable.Fluid 50;
        Uas_Consumable.Bulk 7;

        Inventory.PickupMessage "$CC_PLTMIXIN_PICKUP";

        // Sprite stuff goes here. Dont leave entirely to Ted. -- [Kattie]
    }

}