mixin class CC_ExampleMRE
{
    default
    {
        // The specified Calories and Fluids this ration contains. - [Ted]
        UaS_Consumable.Calories "9001";
        UaS_Consumable.Fluids "9001";

        // The rate of spoilage for the ration when unsealed. - [Ted]
        UaS_Consumable.SpoilRate 1.2;
        // How much the ration weighs by default. - [Ted]
        UaS_Consumable.Bulk 22;

        // Whether or not this is a "packaged" item, meaning it is closed when spawned. - [Ted]
        +UaS_Consumable.PACKAGED;
        // Whether or not the ration is to be drank. - [Ted]
        +UaS_Consumable.DRINKABLE;
        // Whether or not this ration can be resealed, meaning it's not a "rip open" style of packaging. - [Ted]
        +UaS_Consumable.RESEALABLE;
        // Blacklist the ration from being spawned by UaS. - [Ted]
        +UaS_Consumable.NOSPAWN

        // What sound to play when the ration is opened. - [Ted]
        UaS_Consumable.OpenSound "UaS/FoodOpen"
        // What sound to play when the ration is consumed. - [Ted]
        UaS_Consumable.ConsumeSound "";



        // What to use as the sprite for the inventory icon. - [Ted]
        Inventory.Icon "";
        // What to log when the item is picked up. - [Ted]
        Inventory.PickupMessage "";
        // What the tag of the item is. Displayed when hovered over with 'Zoom' plus some other places. - [Ted]
        tag "";

        // The description of the ration that is shown when held. - [Ted]
        UaS_Consumable.Description "";

        // How much to scale the sprite up/down by. - [Ted]
        Scale 1.15;
    }

    // Allows specifying custom messages whenever the user interacts with the ration. - [Ted]
    override void Messages()
    {
        AddOpenText ("Opened the package! Wowie!");
        AddOpenText ("I opened it AGAIN!!! Wowie!");
        AddConsumeText ("mgjdngsjkhn jsfnjklhjhn j YUMMY!!!!! WOWIE!!!!");
        AddConsumeText ("YOU CAN EVEN ADD MULTIPLE!!!! WOWIE!!!!");
    }
     
    // Allows adding contents to the ration that the player is given whenever it's opened. - [Ted]
    override void Contents()
    {
        AddItem ("ZM66AssaultRifle");
    }

    // Allows adding custom actions to their respective "states". - [Ted]
    override void OnOpen(){}
    override void OnClose(){}
    override void OnConsume(){}
}